---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: micros
  name: users-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-app
  template:
    metadata:
      labels:
        app: users-app
    spec:
      containers:
        - name: app
          image: micros-registry:35545/users:latest
          imagePullPolicy: IfNotPresent
          readinessProbe:
            httpGet:
              path: /
              port: api-port
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              memory: "200Mi"
              cpu: "100m"
          ports:
            - containerPort: 3000
              name: api-port
---
apiVersion: v1
kind: Service
metadata:
  namespace: micros
  name: users-app-service
spec:
  selector:
    app: users-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: api-port
      name: api-port

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: users-app
  namespace: micros
  labels:
    name: users-app
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: users-app-service
                port:
                  number: 80

---

